#!/usr/bin/env bash
# scp command into a server to xfer file
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -o IdentityFile="$4" "$1" "$3@$2":~/
fi
