#!/usr/bin/env bash
# Readme:
# Replace a line with multiple lines with sed
# Configure your Nginx server so that
# /redirect_me is redirecting to another page.
# -
# Requirements:
# The redirection must be a “301 Moved Permanently”
# You answer file should be a Bash script containing
# commands to automatically configure a
# Ubuntu machine to respect above requirements
# -
# Using what you did with 1-install_nginx_web_server,
# write 3-redirection so that it configures a brand new 
# Ubuntu machine to the requirements asked in this task

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "0,/location \/ {/s//location \/redirect_me {\n\t\treturn 301 \$scheme:\/\/https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation \/ {/" /etc/nginx/sites-available/default
service nginx restart
