#!/usr/bin/env bash
#
# Configure your Nginx server to have a custom 404
# page that contains the string Ceci n'est pas une page.
# Requirements:
# The page must return an HTTP 404 error code
# The page must contain the string Ceci n'est pas une page
# Using what you did with 3-redirection, write 4-not_found_page_404
# so that it configures a brand new Ubuntu machine
# to the requirements asked in this task

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html

# sudo sed -i "0,/location \/ {/s//error_page 404 \/custom_404.html;\n\n\tlocation \/redirect_me {\n\t\treturn 301 \$scheme:\/\/https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation \/ {/" /etc/nginx/sites-available/default
new="\terror_page 404 /custom_404.html;\n\n\tlocation /redirect_me {\n\treturn 301 \$scheme://https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
old="\tlocation / {"
sudo sed -i "s@^$old@$new@" /etc/nginx/sites-available/default
sudo touch /var/www/html/custom_404.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo service nginx restart
