#!/usr/bin/env bash
#Write a Bash script that displays Holberton School
#10 times, but for the 9th iteration, displays
#Holberton School and then Hi on a new line
x=1
while [ $x -le 10 ]
do
	if [ $x != 9 ]
	then
	   echo "Holberton School"
	else
	   echo "Holberton School"
	   echo "Hi"
	fi
	((x++))
done
