#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10 and:
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Holberton School for the other iterations
# Requirements:
# You must use the while loop (for and until are forbidden)
# You must use the if, elif and else statements
x=0
while [ $x -lt 10 ];
do
if [ $x -eq 3 ]
then
    echo "bad luck"
elif [ $x -eq 7 ]
then
    echo "good luck"
else
    echo "Holberton School"
fi
((x++))
done
