#!/usr/bin/env bash
# Write a Bash script that gives you information about the holbertonschool file.
# Requirements:
# You must use if and, else (case is forbidden)
# Your Bash script should check if the file exists and print:
# if the file exists: holbertonschool file exists
# if the file does not exist: holbertonschool file does not exist
# If the file exists, print:
# if the file is empty: holbertonschool file is empty
# if the file is not empty: holbertonschool file is not empty
# if the file is a regular file: holbertonschool is a regular file
# if the file is not a regular file: (nothing)
x="holbertonschool"
if [ -e $x ]
   then
   echo $x file exists
   	if [ -s $x ]
   	then
	echo $x file is not empty
   	else
	echo $x file is empty
   	fi
   if [ -f $x ]
   then
   echo $x is a regular file
   fi
else
echo $x file does not exist
fi
